- name: Setup and start Minecraft server
  hosts: minecraft
  become: true

  tasks:
    - name: Copy start_minecraft.sh script to server
      ansible.builtin.copy:
        src: ../script/start_mc.sh
        dest: /home/ec2-user/start_mc.sh
        mode: '0755'

    - name: Copy reboot.sh script to server
      ansible.builtin.copy:
        src: ../script/create_reboot.sh
        dest: /home/ec2-user/create_reboot.sh
        mode: '0755'
        
    - name: Run start_minecraft.sh script
      ansible.builtin.shell: /home/ec2-user/start_mc.sh
      args:
        executable: /bin/bash

    - name: Run create_reboot script
      ansible.builtin.shell: /home/ec2-user/create_reboot.sh
      args:
        executable: /bin/bash
