name: Terraform Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Initialize Terraform
      run: terraform init
      working-directory: ./terraform

    - name: Apply Terraform configuration
      run: |
        cd terraform
        terraform apply -auto-approve
        terraform output -json
        terraform output -json | jq -r '.instance_ip.value' > ../terraform/instance_public_ip.txt
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
        AWS_REGION: us-west-2  # Specify the desired region here

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Ansible
      run: pip install ansible

    - name: Setup SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_KEY_PEM }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Create Ansible inventory
      run: |
        INSTANCE_IP=$(cat terraform/instance_public_ip.txt)
        echo "[minecraft]" > ansible_hosts
        echo "$INSTANCE_IP ansible_user=ec2-user ansible_ssh_private_key_file=~/.ssh/id_rsa ansible_ssh_common_args='-o StrictHostKeyChecking=no'" >> ansible_hosts

    - name: Display Ansible inventory
      run: cat ansible_hosts
      
    - name: Run Ansible playbook
      run: ansible-playbook -i ansible_hosts ansible/playbook.yml

    - name: Check Minecraft server with nmap
      run: |
        sudo apt update && sudo apt install -y nmap
        INSTANCE_IP=$(cat terraform/instance_public_ip.txt)
        sleep 15
        nmap -sV -Pn -p T:25565 $INSTANCE_IP

    - name: Output Ip
      run: terraform output -json | jq -r '.instance_ip.value'
